# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
  log_file: "%kernel.root_dir%/../var/logs/app.log"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  foo_service:
    class: AppBundle\Service\FooService

  log_service:
    class: AppBundle\Service\LogService
    arguments: ["%log_file%"]
