# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
  log_file: "%kernel.root_dir%/../var/logs/app.log"
  redis.host: redis
  redis.port: 6379

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  redis_service:
    class: AppBundle\Service\RedisService
    arguments: ["%redis.host%", "%redis.port%"]
